# Generated by Django 2.2.6 on 2019-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191109_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50, unique=True)),
                ('p_price', models.FloatField()),
                ('p_quantity', models.IntegerField()),
            ],
        ),
    ]
